import 'dart:typed_data';

import 'package:image/image.dart' as img;

import 'phash_cos_table.dart';

/// Inset fractions for multi-scale matching (strips the sleeve margin). 0% =
/// no-sleeve; 3–6% covers typical sleeves. Validated: recovers all sleeved
/// benchmark cards to rank #1.
const List<double> kInsets = [0.0, 0.02, 0.03, 0.04, 0.05, 0.06];

/// On-device DCT perceptual hash (64-bit) — the Dart half of the parity contract
/// (Section 5). This MUST produce bit-identical results to dataprep/phash.py for
/// the same input image. See app/test/phash_parity_test.dart.
///
/// The algorithm and every parity decision mirror phash.py:
///   * IEEE-754 double arithmetic with a fixed operation order.
///   * Grayscale rounding pinned to floor(x + 0.5) (NOT .round(), which is
///     half-away-from-zero and differs from Python's banker's rounding).
///   * Deterministic area/box resize (hand-rolled, not img.copyResize).
///   * DCT basis read from the SHARED cosine table (phash_cos_table.dart),
///     generated by phash.py, so cross-runtime cos() differences cannot break
///     parity.
class PerceptualHash {
  // --- Diagnostics (instrumentation only; does NOT affect the hash) ----------
  // Sub-step time accumulators (microseconds), summed across the multiScale
  // insets inside fromImage and read back via [lastMultiScaleTimings]. Safe
  // because fromImage is synchronous + non-reentrant within an isolate, and one
  // multiScale runs at a time in the frame-processor isolate.
  static int _accGrayUs = 0, _accResizeUs = 0, _accDctUs = 0, _accPackUs = 0;
  static final Stopwatch _accSw = Stopwatch();

  /// Sub-step breakdown (ms) of the last [multiScale] call:
  /// gray / crop / resize / dct / pack. Diagnostic only.
  static Map<String, int> lastMultiScaleTimings = const {};

  /// Decode bytes and compute the 256-bit pHash (32-byte big-endian blob).
  static Uint8List fromBytes(Uint8List bytes) {
    final decoded = img.decodeImage(bytes);
    if (decoded == null) {
      throw const FormatException('Could not decode image for pHash');
    }
    return fromImage(decoded);
  }

  /// 256-bit hash as a 32-byte big-endian blob (matches phash.py to_bytes()).
  static Uint8List fromImage(img.Image image) {
    _accSw
      ..reset()
      ..start();
    final gray = _toGray(image);
    _accGrayUs += _accSw.elapsedMicroseconds;
    _accSw
      ..reset()
      ..start();
    final resized = _resizeBox(gray, image.width, image.height);
    _accResizeUs += _accSw.elapsedMicroseconds;
    _accSw
      ..reset()
      ..start();
    final block = _dct8x8(resized);
    _accDctUs += _accSw.elapsedMicroseconds;
    _accSw
      ..reset()
      ..start();
    final out = _pack(block);
    _accPackUs += _accSw.elapsedMicroseconds;
    return out;
  }

  /// Multi-scale hashes of a warped card at several inset crops. The card
  /// detector locks onto the SLEEVE edge, so a sleeved card sits inset ~3–6% in
  /// the warp; hashing at a few insets and matching each lets the matcher pick
  /// the crop that strips the sleeve margin. No-sleeve cards win at 0%.
  static List<Uint8List> multiScale(img.Image card, {List<double> insets = kInsets}) {
    _accGrayUs = _accResizeUs = _accDctUs = _accPackUs = 0;
    var cropUs = 0;
    final cropSw = Stopwatch();
    final w = card.width, h = card.height;
    final out = <Uint8List>[];
    for (final p in insets) {
      if (p <= 0) {
        out.add(fromImage(card));
        continue;
      }
      final dx = (w * p).round(), dy = (h * p).round();
      final cw = w - 2 * dx, ch = h - 2 * dy;
      if (cw < 16 || ch < 16) {
        out.add(fromImage(card));
      } else {
        cropSw
          ..reset()
          ..start();
        final cropped = img.copyCrop(card, x: dx, y: dy, width: cw, height: ch);
        cropUs += cropSw.elapsedMicroseconds;
        out.add(fromImage(cropped));
      }
    }
    lastMultiScaleTimings = {
      'gray': (_accGrayUs / 1000).round(),
      'crop': (cropUs / 1000).round(),
      'resize': (_accResizeUs / 1000).round(),
      'dct': (_accDctUs / 1000).round(),
      'pack': (_accPackUs / 1000).round(),
    };
    return out;
  }

  /// Hex string of the 32-byte hash, matching phash.py's `{h:064x}`.
  static String toHex(Uint8List bytes) {
    final sb = StringBuffer();
    for (final b in bytes) {
      sb.write(b.toRadixString(16).padLeft(2, '0'));
    }
    return sb.toString();
  }

  /// Convert a 32-byte big-endian hash to 4 signed 64-bit words (for popcount).
  static Int64List toWords(Uint8List bytes) {
    final bd = ByteData.sublistView(bytes);
    final words = Int64List(4);
    for (var i = 0; i < 4; i++) {
      words[i] = bd.getInt64(i * 8, Endian.big);
    }
    return words;
  }

  // --- Step 2: grayscale (Y = 0.299R + 0.587G + 0.114B, floor(.+0.5)) -------
  static List<Int32List> _toGray(img.Image image) {
    final w = image.width;
    final h = image.height;
    final out = List<Int32List>.generate(h, (_) => Int32List(w), growable: false);
    for (var y = 0; y < h; y++) {
      final row = out[y];
      for (var x = 0; x < w; x++) {
        final p = image.getPixel(x, y);
        final r = p.r.toDouble();
        final g = p.g.toDouble();
        final b = p.b.toDouble();
        var yy = (0.299 * r + 0.587 * g + 0.114 * b + 0.5).floor();
        if (yy < 0) {
          yy = 0;
        } else if (yy > 255) {
          yy = 255;
        }
        row[x] = yy;
      }
    }
    return out;
  }

  // --- Step 3: deterministic area/box resize to kResizeN x kResizeN ---------
  static List<Float64List> _resizeBox(List<Int32List> gray, int w, int h) {
    const n = kResizeN;
    final out = List<Float64List>.generate(n, (_) => Float64List(n), growable: false);
    for (var oy = 0; oy < n; oy++) {
      final y0 = oy * h / n;
      final y1 = (oy + 1) * h / n;
      for (var ox = 0; ox < n; ox++) {
        final x0 = ox * w / n;
        final x1 = (ox + 1) * w / n;
        var total = 0.0;
        var area = 0.0;
        var iy = y0.floor();
        while (iy < y1) {
          final top = iy > y0 ? iy.toDouble() : y0;
          final bot = (iy + 1) < y1 ? (iy + 1).toDouble() : y1;
          final fy = bot - top;
          if (fy > 0.0) {
            final grow = gray[iy];
            var ix = x0.floor();
            while (ix < x1) {
              final left = ix > x0 ? ix.toDouble() : x0;
              final right = (ix + 1) < x1 ? (ix + 1).toDouble() : x1;
              final fx = right - left;
              if (fx > 0.0) {
                final wgt = fx * fy;
                total += grow[ix] * wgt;
                area += wgt;
              }
              ix++;
            }
          }
          iy++;
        }
        out[oy][ox] = total / area;
      }
    }
    return out;
  }

  // --- Step 4: 2-D DCT-II, top-left kDctKeep x kDctKeep block ---------------
  static List<Float64List> _dct8x8(List<Float64List> matrix) {
    const n = kResizeN;
    const k = kDctKeep;
    // Row pass: tmp[y][u]
    final tmp = List<Float64List>.generate(n, (_) => Float64List(k), growable: false);
    for (var y = 0; y < n; y++) {
      final row = matrix[y];
      for (var u = 0; u < k; u++) {
        final cosU = kCos[u];
        var s = 0.0;
        for (var x = 0; x < n; x++) {
          s += row[x] * cosU[x];
        }
        tmp[y][u] = s * kAlpha[u];
      }
    }
    // Column pass: out[v][u]
    final out = List<Float64List>.generate(k, (_) => Float64List(k), growable: false);
    for (var u = 0; u < k; u++) {
      for (var v = 0; v < k; v++) {
        final cosV = kCos[v];
        var s = 0.0;
        for (var y = 0; y < n; y++) {
          s += tmp[y][u] * cosV[y];
        }
        out[v][u] = s * kAlpha[v];
      }
    }
    return out;
  }

  // --- Steps 5-8: threshold + pack (row-major, MSB first) ------------------
  static Uint8List _pack(List<Float64List> block) {
    const k = kDctKeep;
    const bits = k * k; // 256
    final flat = Float64List(bits);
    var i = 0;
    for (var v = 0; v < k; v++) {
      for (var u = 0; u < k; u++) {
        flat[i++] = block[v][u];
      }
    }
    // Median of the non-DC coefficients (exclude index 0).
    final rest = flat.sublist(1).toList()..sort((a, b) => a.compareTo(b));
    final median = rest[rest.length ~/ 2];

    // MSB-first packing: bit j (0=most significant) -> byte j~/8, bit 7-(j%8).
    final out = Uint8List(bits ~/ 8);
    for (var j = 0; j < bits; j++) {
      if (flat[j] > median) {
        out[j >> 3] |= 1 << (7 - (j & 7));
      }
    }
    return out;
  }
}

/// Hamming distance between two 32-byte (256-bit) hashes (Section 5.2).
int hammingDistance(Uint8List a, Uint8List b) {
  var count = 0;
  for (var i = 0; i < a.length; i++) {
    var v = a[i] ^ b[i];
    while (v != 0) {
      v &= v - 1;
      count++;
    }
  }
  return count;
}
