import 'dart:typed_data';

import 'package:image/image.dart' as img;

import 'phash_cos_table.dart';

/// On-device DCT perceptual hash (64-bit) — the Dart half of the parity contract
/// (Section 5). This MUST produce bit-identical results to dataprep/phash.py for
/// the same input image. See app/test/phash_parity_test.dart.
///
/// The algorithm and every parity decision mirror phash.py:
///   * IEEE-754 double arithmetic with a fixed operation order.
///   * Grayscale rounding pinned to floor(x + 0.5) (NOT .round(), which is
///     half-away-from-zero and differs from Python's banker's rounding).
///   * Deterministic area/box resize (hand-rolled, not img.copyResize).
///   * DCT basis read from the SHARED cosine table (phash_cos_table.dart),
///     generated by phash.py, so cross-runtime cos() differences cannot break
///     parity.
class PerceptualHash {
  /// Decode bytes and compute the 64-bit pHash. The returned [int] is Dart's
  /// native 64-bit signed value, i.e. the same bit pattern stored (signed) in
  /// the bundle `hashes` table.
  static int fromBytes(Uint8List bytes) {
    final decoded = img.decodeImage(bytes);
    if (decoded == null) {
      throw const FormatException('Could not decode image for pHash');
    }
    return fromImage(decoded);
  }

  static int fromImage(img.Image image) {
    final gray = _toGray(image);
    final resized = _resizeBox(gray, image.width, image.height);
    final block = _dct8x8(resized);
    return _pack(block);
  }

  /// Hex string of the unsigned 64-bit value, matching phash.py's `{h:016x}`.
  static String toHex64(int v) {
    final hi = (v >> 32) & 0xFFFFFFFF;
    final lo = v & 0xFFFFFFFF;
    return hi.toRadixString(16).padLeft(8, '0') +
        lo.toRadixString(16).padLeft(8, '0');
  }

  // --- Step 2: grayscale (Y = 0.299R + 0.587G + 0.114B, floor(.+0.5)) -------
  static List<Int32List> _toGray(img.Image image) {
    final w = image.width;
    final h = image.height;
    final out = List<Int32List>.generate(h, (_) => Int32List(w), growable: false);
    for (var y = 0; y < h; y++) {
      final row = out[y];
      for (var x = 0; x < w; x++) {
        final p = image.getPixel(x, y);
        final r = p.r.toDouble();
        final g = p.g.toDouble();
        final b = p.b.toDouble();
        var yy = (0.299 * r + 0.587 * g + 0.114 * b + 0.5).floor();
        if (yy < 0) {
          yy = 0;
        } else if (yy > 255) {
          yy = 255;
        }
        row[x] = yy;
      }
    }
    return out;
  }

  // --- Step 3: deterministic area/box resize to kResizeN x kResizeN ---------
  static List<Float64List> _resizeBox(List<Int32List> gray, int w, int h) {
    const n = kResizeN;
    final out = List<Float64List>.generate(n, (_) => Float64List(n), growable: false);
    for (var oy = 0; oy < n; oy++) {
      final y0 = oy * h / n;
      final y1 = (oy + 1) * h / n;
      for (var ox = 0; ox < n; ox++) {
        final x0 = ox * w / n;
        final x1 = (ox + 1) * w / n;
        var total = 0.0;
        var area = 0.0;
        var iy = y0.floor();
        while (iy < y1) {
          final top = iy > y0 ? iy.toDouble() : y0;
          final bot = (iy + 1) < y1 ? (iy + 1).toDouble() : y1;
          final fy = bot - top;
          if (fy > 0.0) {
            final grow = gray[iy];
            var ix = x0.floor();
            while (ix < x1) {
              final left = ix > x0 ? ix.toDouble() : x0;
              final right = (ix + 1) < x1 ? (ix + 1).toDouble() : x1;
              final fx = right - left;
              if (fx > 0.0) {
                final wgt = fx * fy;
                total += grow[ix] * wgt;
                area += wgt;
              }
              ix++;
            }
          }
          iy++;
        }
        out[oy][ox] = total / area;
      }
    }
    return out;
  }

  // --- Step 4: 2-D DCT-II, top-left kDctKeep x kDctKeep block ---------------
  static List<Float64List> _dct8x8(List<Float64List> matrix) {
    const n = kResizeN;
    const k = kDctKeep;
    // Row pass: tmp[y][u]
    final tmp = List<Float64List>.generate(n, (_) => Float64List(k), growable: false);
    for (var y = 0; y < n; y++) {
      final row = matrix[y];
      for (var u = 0; u < k; u++) {
        final cosU = kCos[u];
        var s = 0.0;
        for (var x = 0; x < n; x++) {
          s += row[x] * cosU[x];
        }
        tmp[y][u] = s * kAlpha[u];
      }
    }
    // Column pass: out[v][u]
    final out = List<Float64List>.generate(k, (_) => Float64List(k), growable: false);
    for (var u = 0; u < k; u++) {
      for (var v = 0; v < k; v++) {
        final cosV = kCos[v];
        var s = 0.0;
        for (var y = 0; y < n; y++) {
          s += tmp[y][u] * cosV[y];
        }
        out[v][u] = s * kAlpha[v];
      }
    }
    return out;
  }

  // --- Steps 5-8: threshold + pack (row-major, MSB first) ------------------
  static int _pack(List<Float64List> block) {
    const k = kDctKeep;
    final flat = Float64List(k * k);
    var i = 0;
    for (var v = 0; v < k; v++) {
      for (var u = 0; u < k; u++) {
        flat[i++] = block[v][u];
      }
    }
    // Median of the 63 non-DC coefficients (exclude index 0).
    final rest = flat.sublist(1).toList()..sort((a, b) => a.compareTo(b));
    final median = rest[rest.length ~/ 2]; // 63 -> index 31

    var bits = 0;
    for (var j = 0; j < 64; j++) {
      bits = (bits << 1) | (flat[j] > median ? 1 : 0);
    }
    return bits;
  }
}

/// Hamming distance via popcount(a XOR b) (Section 5.2).
int hammingDistance(int a, int b) {
  var x = a ^ b;
  var count = 0;
  // Process 64 bits; works for the signed two's-complement representation.
  for (var i = 0; i < 64; i++) {
    count += x & 1;
    x >>>= 1; // logical shift so the sign bit doesn't smear
  }
  return count;
}
